# Generated by Django 3.0.9 on 2020-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, upload_to='original', verbose_name='Загрузка с компьютера')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('resize', models.ImageField(blank=True, upload_to='resize', verbose_name='Отредактированное изображение')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина')),
            ],
        ),
    ]
