# Generated by Django 3.0.9 on 2020-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, default=0, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='original', verbose_name='Загрузка с компьютера'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resize_image',
            field=models.ImageField(blank=True, upload_to='resize', verbose_name='Отредактированное изображение'),
        ),
    ]
